
[[Snippets]]
  Description = "Scan dir for something which looks like api keys"
  Output = ""
  Tag = []
  command = "grep -r -E '(api_key|secret|token|[A-Za-z0-9]{20,})' <path_to_dir>"

[[Snippets]]
  Description = "Add / re-add all files in a directory"
  Output = ""
  Tag = []
  command = "chezmoi add -r <path_to_dir>/*"

[[Snippets]]
  Description = "Compile sketch for ESP32"
  Output = ""
  Tag = []
  command = "arduino-cli compile --fqbn esp32:esp32:esp32 <path_to_file>"

[[Snippets]]
  Description = "Upload compiled sketch over serial USB"
  Output = ""
  Tag = []
  command = "arduino-cli upload -p /dev/ttyUSB0 --fqbn esp32:esp32:esp32 <path_to_file>"

[[Snippets]]
  Description = "Generate SSH key for specified email"
  Output = ""
  Tag = []
  command = "ssh-keygen -C <email>"

[[Snippets]]
  Description = "Set the remote URL of a local repo"
  Output = ""
  Tag = []
  command = "git remote set-url origin git@github.com:<username>/<repo name>.git"
