gui:
  theme:
    activeBorderColor:
      - blue
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - default
    selectedRangeBgColor:
      - default
    cherryPickedCommitBgColor:
      - cyan
    cherryPickedCommitFgColor:
      - blue
    unstagedChangesColor:
      - red
    # Optional: Customize more colors for clarity
    defaultFgColor:
      - white
    searchingActiveBorderColor:
      - magenta
    searchingInactiveBorderColor:
      - white
  showFileTree: true
  showListFooter: false
  showRandomTip: true
  showBottomLine: false
  showCommandLog: true
  showIcons: true
  # New: show branch commit counts in branch list (if supported)
  showBranchCommitHash: true
  # Optional: Set split direction if you use tmux/Zellij
  splitDiff: "auto" # or "horizontal" / "vertical"
disableStartupPopups: true
notARepository: 'skip'
os:
  editCommand: 'nvim'
  editCommandTemplate: '{{editor}} +{{line}} -- {{filename}}' # For line-specific editing in Neovim
# Optional: Add custom keybindings for Vim-style navigation
keybinding:
  universal:
    prevItem: 'k'
    nextItem: 'j'
    # prevPage: 'ctrl+u'
    # nextPage: 'ctrl+d'
    togglePanel: '`' # Backtick as leader, as per your preference[2]
    quit: 'q'
  files:
    toggleStagedAll: 'S'
    toggleTreeView: 'T'
    # Add more as needed
# Optional: Enhance performance for large repos
performance:
  enableLazyLoading: true
# Optional: Miscellaneous
promptToReturnFromSubprocess: false
