theme = "rose_pine"

[editor]
line-number = "relative"
mouse = false
cursorline = true
true-color = true
evil = true
auto-completion = true
path-completion = true
auto-format = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
character = "▏"
render = true

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.lsp]
enable = true
display-progress-messages = true
auto-signature-help = true
snippets = true
