[default_apps]
# teams = "teams-for-linux --enable-features=UseOzonePlatform --ozone-platform=wayland --url {meeting_url}"
# calendar_client = "thunderbird"
# terminal = "ghostty"
# browser = "/opt/zen-browser-bin/zen-bin %u"

[units]
lengths = "meters"
weights = "kg"
volumes = "l"
temperatures = "C"
currency = "nzd"

[debug]
try_suppress_errors = false
try_suppress_warnings = false
app_paths = []

[appearance]
width = 900
height = 500
gsk_renderer = "cairo"
icon_paths = ["testconfig/icons"]
icon_size = 22
use_base_css = true
opacity = 1.0
mod_key_ascii = ["⇧", "⇧", "⌘", "⌘", "⎇", "✦", "✦", "⌘"]

[behavior]
use_xdg_data_dir_icons = false
animate = true

[binds]
up = "control-k"
down = "control-j"
left = "control-h"
right = "control-l"
context = "control-i"
modifier = "control"
exec_inplace = "control-return"

[files]
config = "/home/user/.config/sherlock/config.toml"
css = "/home/user/.config/sherlock/main.css"
fallback = "/home/user/.config/sherlock/fallback.json"
alias = "/home/user/.config/sherlock/sherlock_alias.json"
ignore = "/home/user/.config/sherlock/sherlockignore"
actions = "/home/user/.config/sherlock/sherlock_actions.json"

[runtime]
multi = false
center = false
photo_mode = false
display_raw = false
daemonize = false

[caching]
enable = true
cache = "/home/user/.cache/sherlock/sherlock_desktop_cache.json"

[expand]
enable = false
edge = "top"
margin = 0

# Dims everything else
[backdrop]
enable = false
opacity = 0.6
edge = "top"

[status_bar]
enable = true

[search_bar_icon]
enable = true
icon = "system-search-symbolic"
icon_back = "go-previous-symbolic"
size = 22
